import asyncio
import logging
import time
from typing import List, Dict, Any, Optional

from src.tools import github_tools
from src.core.github_ui import GitHubUI
from src.core.chat_manager import ChatManager
from src.infrastructure.gemini.adapter import GeminiAdapter
from src.infrastructure.nvidia.adapter import NvidiaAdapter
from src.core.config_manager import ConfigManager
from src.tools.registry import AVAILABLE_TOOLS

logger = logging.getLogger("src")

class GitHubModeOrchestrator:
    """
    Orchestrates the execution of paser-mini in GitHub mode.
    All communication is generated by the AI, no hardcoded templates.
    """

    def __init__(self, system_instruction: str):
        self.system_instruction = system_instruction
        self.config_manager = ConfigManager()
        self.processing_label = "paser-processing"
        self.trigger_hashtag = "#ai-assistance"
        self.bot_login = None

    async def run(self):
        """Main entry point for GitHub mode."""
        logger.info("Starting GitHub Mode Orchestrator...")
        try:
            user_data = github_tools.get_authenticated_user()
            self.bot_login = user_data.get("login")
            logger.info(f"Authenticated as bot: {self.bot_login}")

            issues = github_tools.list_issues()
            eligible_issues = self._filter_issues(issues)
            
            if not eligible_issues:
                logger.info("No eligible issues found.")
                return

            for issue in eligible_issues:
                await self.process_issue(issue)

        except Exception as e:
            logger.exception(f"Critical error in GitHub mode: {e}")

    def _filter_issues(self, issues: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        eligible = []
        for issue in issues:
            body = issue.get("body") or ""
            labels = [l["name"] for l in issue.get("labels", [])]
            if self.trigger_hashtag in body and self.processing_label not in labels:
                eligible.append(issue)
        return eligible

    async def process_issue(self, issue: Dict[str, Any]):
        issue_number = issue["number"]
        issue_body = issue.get("body", "")
        
        logger.info(f"Processing issue #{issue_number}...")
        
        try:
            # 1. Mark as processing
            github_tools.add_label(issue_number, self.processing_label)
            
            # 2. Consume the trigger hashtag
            new_body = issue_body.replace(self.trigger_hashtag, "").strip()
            if new_body != issue_body:
                github_tools.edit_issue(issue_number, body=new_body)

            # 3. Setup Agent
            ui = GitHubUI(issue_number=issue_number)
            provider = self.config_manager.get("provider", "Gemini")
            assistant = NvidiaAdapter() if provider == "NVIDIA" else GeminiAdapter()
            
            chat_manager = ChatManager(
                assistant, AVAILABLE_TOOLS, self.system_instruction, ui, instance_mode=True
            )

            # 4. Execution with Feedback Loop
            last_comment_id = self._get_last_comment_id(issue_number)
            
            # We wrap the initial input to guide the AI to acknowledge and plan
            initial_prompt = (
                f"SYSTEM: You have been assigned to GitHub Issue #{issue_number}.\n"
                f"Issue Description: {issue_body}\n\n"
                f"Please acknowledge the request, analyze the problem, and provide a detailed plan of action to the user."
            )
            
            run_task = asyncio.create_task(chat_manager.run(initial_input=initial_prompt))
            
            while not run_task.done():
                comment_data = await self._wait_for_comment(issue_number, last_comment_id)
                if comment_data:
                    new_comment, new_id = comment_data
                    last_comment_id = new_id
                    
                    logger.info(f"User feedback received on issue #{issue_number}. Interrupting...")
                    
                    chat_manager.stop_execution()
                    await chat_manager.message_queue.put(new_comment)
                
                await asyncio.sleep(30)

            await run_task

        except Exception as e:
            logger.exception(f"Error processing issue #{issue_number}: {e}")
            # Minimal error report, as we avoid automatic conversational messages
            github_tools.post_comment(issue_number, f"Error: {str(e)}")
        finally:
            try:
                github_tools.remove_label(issue_number, self.processing_label)
            except Exception as e:
                logger.error(f"Failed to remove label from issue #{issue_number}: {e}")

    def _get_last_comment_id(self, issue_number: int) -> int:
        comments = github_tools.get_issue_comments(issue_number)
        if not comments:
            return 0
        return comments[-1]["id"]

    async def _wait_for_comment(self, issue_number: int, last_id: int):
        try:
            comments = github_tools.get_issue_comments(issue_number)
            if not comments:
                return None

            human_comments = [c for c in comments if c['user']['login'] != self.bot_login]
            if human_comments and human_comments[-1]["id"] > last_id:
                comment_body = human_comments[-1]["body"]
                if f"@{self.bot_login}" in comment_body:
                    return comment_body, human_comments[-1]["id"]
        except Exception as e:
            logger.error(f"Error polling comments: {e}")
        return None
