import { z } from "zod";

const SCHEMAS = {
  analysis: z.object({ path: z.string() }).strict(),
  arrange: z.object({ file_path: z.string(), path: z.string() }).strict(),
  ast: z.object({ path: z.string(), query: z.string(), limit: z.number().optional() }).strict(),
  bin: z.object({
    action: z.enum(["inspect", "extract", "search", "detect", "convert"]),
    filePath: z.string().optional(),
    offset: z.number().optional(),
    length: z.number().optional(),
    end: z.number().optional(),
    outputFile: z.string().optional(),
    pattern: z.string().optional(),
    hexString: z.string().optional(),
    type: z.enum(["Int8", "UInt8", "Int16", "UInt16", "Int32", "UInt32", "Float32", "Float64"]).optional(),
    endianness: z.enum(["LE", "BE"]).optional(),
  }),
  close: z.object({ issue_number: z.number().int(), repo: z.string().optional() }).strict(),
  concat: z.object({ destination: z.string(), source: z.string() }).strict(),
  copy: z.object({ origin: z.string(), destination: z.string() }).strict(),
  create: z.object({ title: z.string(), body: z.string(), repo: z.string().optional() }).strict(),
  diff: z.object({ path: z.string() }).strict(),
  doc: z.object({ path: z.string().optional().default("."), outputDir: z.string().optional().default("docs/api") }),
  edit: z.object({ issue_number: z.number().int(), repo: z.string().optional(), title: z.string().optional(), body: z.string().optional() }).strict(),
  eslint: z.object({ path: z.string().optional().default(".") }),
  eval: z.object({ code: z.string() }).strict(),
  execute: z.object({ command: z.string() }),
  glob: z.object({ pattern: z.string() }).strict(),
  grep: z.object({ query: z.string(), path: z.string().optional() }).strict(),
  img: z.object({ path: z.string(), crop: z.array(z.number()).length(4).optional() }).strict(),
  inspect: z.object({ path: z.string().optional().or(z.null()), command: z.string().optional() }).strict(),
  issues: z.object({ repo: z.string().optional() }).strict(),
  list: z.object({ path: z.string() }).strict(),
  message: z.object({
    id: z.string(),
    timestamp: z.string(),
    role: z.enum(["user", "agent", "system", "thought", "tool"]),
    nickname: z.string(),
    content: z.string(),
    metadata: z.object({
      tool_call: z.object({ id: z.string(), name: z.string(), args: z.record(z.any()) }).optional(),
      tool_response: z.object({ id: z.string(), status: z.enum(["OK", "ERR"]), result: z.any().optional() }).optional(),
      is_noise: z.boolean().optional(),
    }).optional(),
  }),
  metrics: z.object({}).strict(),
  mkdir: z.object({ path: z.string() }).strict(),
  nickname: z.object({ newNickname: z.string().min(1).max(32) }).strict(),
  node: z.object({ file_path: z.string(), path: z.string() }).strict(),
  notify: z.object({ message: z.string() }).strict(),
  patch: z.object({ patch: z.string() }).strict(),
  post: z.object({ issue_number: z.number().int(), body: z.string(), repo: z.string() }).strict(),
  push: z.object({ data: z.any() }).strict(),
  read: z.object({ path: z.string() }).strict(),
  tail: z.object({ path: z.string(), tail: z.union([z.number(), z.string()]) }).strict(),
  real: z.object({ action: z.string() }).strict(),
  reloadTools: z.object({}).strict(),
  remote: z.object({}).strict(),
  remove: z.object({ path: z.string() }).strict(),
  rename: z.object({ origin: z.string(), destination: z.string() }).strict(),
  replace: z.object({ path: z.string(), search_text: z.string(), replace_text: z.string() }).strict(),
  reset: z.object({ user_message: z.string() }).strict(),
  restore: z.object({ filepath: z.string() }).strict(),
  run: z.object({ code: z.string() }).strict(),
  scene: z.object({ scene: z.string(), action: z.string() }).strict(),
  sed: z.object({ path: z.string(), pattern: z.string(), replacement: z.string().optional(), flags: z.string().optional() }).strict(),
  search: z.object({ query: z.string().min(1, "Search query cannot be empty") }),
  snapshot: z.object({ path: z.string() }).strict(),
  structure: z.object({ file_path: z.string(), path: z.string() }).strict(),
  token: z.object({}).strict(),
  tree: z.object({}).strict(),
  update: z.object({ file_path: z.string(), path: z.string(), value: z.any() }).strict(),
  url: z.object({ url: z.string().url("Invalid URL format") }),
  fetch: z.object({ url: z.string().url("Invalid URL format") }),
  valide: z.object({ json_string: z.string() }).strict(),
  write: z.object({ path: z.string(), content: z.string() }).strict(),
  zip: z.object({ filePath: z.string() }).strict(),
  index: z.object({ path: z.string().optional().default(".") }).strict(),
  load: z.object({ ids: z.string() }).strict(),
};

export default SCHEMAS;
